# Generated by Django 3.0.6 on 2020-06-09 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20200609_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='path',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
