# Generated by Django 3.0.6 on 2020-06-09 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20200609_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='miniature',
            field=models.ImageField(default='exit', upload_to='images/'),
            preserve_default=False,
        ),
    ]
