# Generated by Django 3.0.6 on 2020-06-09 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_post_miniature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='postImages',
        ),
        migrations.AddField(
            model_name='post',
            name='postImages',
            field=models.ImageField(default='exit', upload_to='images/'),
            preserve_default=False,
        ),
    ]
